# Generated by Django 5.1.2 on 2025-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='flower_colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='orders.flowercolor', verbose_name='Цвета цветов'),
        ),
        migrations.AddField(
            model_name='product',
            name='flower_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='orders.flowertype', verbose_name='Типы цветов'),
        ),
    ]
