# Generated by Django 5.1.2 on 2025-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_flowercolor_flowertype_product_flower_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowercolor',
            name='color_code',
            field=models.CharField(default='#000000', help_text='Примеры HEX-кодов:<br><strong>Красный:</strong> #FF0000<br><strong>Белый:</strong> #FFFFFF<br><strong>Желтый:</strong> #FFFF00<br><strong>Черный:</strong> #000000<br><strong>Салатовый:</strong> #32CD32<br><strong>Оранжевый:</strong> #FFA500<br><strong>Фиолетовый:</strong> #800080<br><strong>Синий:</strong> #0000FF', max_length=7, verbose_name='Код цвета (HEX)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowercolor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название цвета'),
        ),
    ]
