# Generated by Django 5.1.2 on 2025-01-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_bouquet_orderitem_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область/Штат')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
