# Generated by Django 5.1.2 on 2024-12-09 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestseller',
            options={'verbose_name': 'Лучший товар', 'verbose_name_plural': 'Лучшие товары'},
        ),
        migrations.AddField(
            model_name='bestseller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestseller',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Метка (например, категория)'),
        ),
    ]
